services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Pour les projets avec un backend, vous pourriez ajouter :
    # depends_on:
    #   - backend
    volumes:
      # Pour la persistance des traductions
      - ../public/locales:/app/public/locales 