import '@fontsource/inter';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { centuryGothic } from './fonts';
import "./globals.css";

const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ["latin"],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${montserrat.variable} ${centuryGothic.variable}`}>
      <body className={`font-sans antialiased bg-white text-gray-800`}>
        {children}
      </body>
    </html>
  );
}
